MUSCLE (3.8) multiple sequence alignment


sp|P0A7G6.2|RECA_ECOLI      ------------------------------------------------------------
sp|P48295.2|RECA_STRVP      ------------------------------------------------------------
sp|O29269.1|RADA_ARCFU      ----------MSE-----------------------------------------------
BAA00913.1                  MSQVQEQHISESQLQYGNGSLMSTVPADLSQSVVDGNGNGSSEDIEATNGSGDGGGLQEQ
sp|P25453.1|DMC1_YEAST      ------MSVTGTEI----------------------------------------------
                                                                                        

sp|P0A7G6.2|RECA_ECOLI      -----------------------------MAIDENKQKALAAALGQIE------------
sp|P48295.2|RECA_STRVP      ------------------------------MAGTDREKALDAALAQIE------------
sp|O29269.1|RADA_ARCFU      ------------ESNEETKIIELEDIP--GVGPETARKLREAGYSTIEAVAVASPSELAN
BAA00913.1                  AEAQGEMEDEAYDEAALGSFVPIEKLQVNGITMADVKKLRESGLHTAEAVAYAPRKDLLE
sp|P25453.1|DMC1_YEAST      ------------DSDTAKNILSVDELQNYGINASDLQKLKSGGIYTVNTVLSTTRRHLCK
                                                                 *   ..    :            

sp|P0A7G6.2|RECA_ECOLI      -KQFGKGSIMRLGE------------------DRSMDVETISTGSLSLDIALGAGGLPMG
sp|P48295.2|RECA_STRVP      -RQFGKGAVMRMGD------------------RTQEPIEVISTGSTALDIALGVGGLPRG
sp|O29269.1|RADA_ARCFU      VGGITEGNAVKIIQAARKLANIGGFESGDKVLERRRSVKKITTGSKDLDELLG-GGVETQ
BAA00913.1                  IKGISEAKADKLLNEAARLVPM-GFVTAADFHMRRSELICLTTGSKNLDTLLG-GGVETG
sp|P25453.1|DMC1_YEAST      IKGLSEVKVEKIKEAAGKIIQV-GFIPATVQLDIRQRVYSLSTGSKQLDSILG-GGIMTM
                               : :    .: :                       :  ::***  **  ** **:   

sp|P0A7G6.2|RECA_ECOLI      RIVEIYGPESSGKTTLTLQVIAAAQ------REGKTCAFIDAEHALDPI----YARKLGV
sp|P48295.2|RECA_STRVP      RVVEIYGPESSGKTTLTLHAVANAQ------KAGGQVAFVDAEHALDPE----YAKKLGV
sp|O29269.1|RADA_ARCFU      AITEFFGEFGSGKTQICHQLAVNVQLPEDEGGLEGSVIIIDTENTFRPERIIQMAEAKGL
BAA00913.1                  SITELFGEFRTGKSQLCHTLAVTCQIPLDIGGGEGKCLYIDTEGTFRPVRLVSIAQRFGL
sp|P25453.1|DMC1_YEAST      SITEVFGEFRCGKTQMSHTLCVTTQLPREMGGGEGKVAYIDTEGTFRPERIKQIAEGYEL
                             :.*.:*    **: :     .  *              :*:* :: *      *    :

sp|P0A7G6.2|RECA_ECOLI      D----IDNLLCSQPDTGEQALEICDALAR-------SGA-VDVIVVDSVAALTPKAEIEG
sp|P48295.2|RECA_STRVP      D----IDNLILSQPDNGEQALEIVDMLVR-------SGA-LDLIVIDSVAALVPRAEIEG
sp|O29269.1|RADA_ARCFU      DGNEVLKNIYVAQAYNSNHQMLLVDNAKELAEKLKKEGRPVRLIIVDSLMSHF-RAEY--
BAA00913.1                  DPDDALNNVAYARAYNADHQLRLLDAAAQMMS----ESR-FSLIVVDSVMALY-RTDF--
sp|P25453.1|DMC1_YEAST      DPESCLANVSYARALNSEHQMELVEQLGEELS----SGD-YRLIVVDSIMANF-RVDY--
                            *    : *:  :.. ..:: : : :           ..    :*::**: :   ..:   

sp|P0A7G6.2|RECA_ECOLI      EIGDSHMGLAARMMSQAMRKLAGNLKQSNTLLIFINQIRMKIG--VMF--GNPETTTGGN
sp|P48295.2|RECA_STRVP      EMGDSHVGLQARLMSQALRKITSALNQSKTTAIFINQLREKIG--VMF--GSPETTTGGR
sp|O29269.1|RADA_ARCFU      -VGRGTLADRQQKLNRHLHDLMKFGELYNAAIVVTNQVMARPD--VLF--GDPTKPVGGH
BAA00913.1                  -SGRGELSARQMHLAKFMRALQRLADQFGVAVVVTNQVVAQVDGGMAF-NPDPKKPIGGN
sp|P25453.1|DMC1_YEAST      -CGRGELSERQQKLNQHLFKLNRLAEEFNVAVFLTNQVQSDPGASALFASADGRKPIGGH
                              * . :.     : . :  :    .   .  .. **:    .    *   .  .. **.

sp|P0A7G6.2|RECA_ECOLI      ALKFYASVRLDIRRIGAVKEGENVVGSETRVKVVKNKIAAPFKQAEFQILYGEGINFYGE
sp|P48295.2|RECA_STRVP      ALKFYASVRLDIRRIETLKDGTDAVGNRTRVKVVKNKVAPPFKQAEFDILYGQGISREGG
sp|O29269.1|RADA_ARCFU      IVAHTATFRIYLKK-------------------------------------GKDDLRIAR
BAA00913.1                  IMAHSSTTRLGFKK-------------------------------------GKGCQRLCK
sp|P25453.1|DMC1_YEAST      VLAHASATRILLRK-------------------------------------GRGDERVAK
                             : . :: *: :..                                     * .      

sp|P0A7G6.2|RECA_ECOLI      LVDLGVKEKLIEKAGAWYSYKGEKIGQGKANATAWLKDNPETAKEIEKKVRELLLSNPNS
sp|P48295.2|RECA_STRVP      LIDMGVEHGFVRKAGAWYTYEGDQLGQGKENARNFLKDNPDLADEIERKIKEKLGVGVRP
sp|O29269.1|RADA_ARCFU      LIDS-----------------------------------PHLPEG---------------
BAA00913.1                  VVDS-----------------------------------PCLPEA---------------
sp|P25453.1|DMC1_YEAST      LQDS-----------------------------------PDMPEK---------------
                            : *                                    *  ..                

sp|P0A7G6.2|RECA_ECOLI      ---------TPDFSVDDSEGVAETNEDF------------------
sp|P48295.2|RECA_STRVP      DAAKAEAATDAAAAADT-AGTDDAAKSVPAPASKTAKATKATAVKS
sp|O29269.1|RADA_ARCFU      ---------EAIFRVTE-RGIEDAEEKDKKKRKK------------
BAA00913.1                  ---------ECVFAIYE-DGVGDPREEDE-----------------
sp|P25453.1|DMC1_YEAST      ---------ECVYVIGE-KGITDSSD--------------------
                                               *  :. .                    
